### PR TITLE
Improve VSCode styling

### PR DESCRIPTION
**Pull request by planger**
* Update GLSP dependency
  * Improve styling for VSCode
  * Change example file to the new format

https://github.com/eclipse-glsp/glsp/issues/492

### CODE REVIEW

**Review by ndoschek — CHANGES_REQUESTED** [review]
Thanks a lot for the update Philip, the diagram in VSCode looks great! :tada: 

I noticed that the resizing of nodes does not work (as well as it doesn't on current master).
The feature table at https://github.com/eclipse-glsp/glsp#features however states it should work. Therefore, due to the unsupported resizing, the category nodes are not properly supported in the VSCode diagram. Could you please have a look at that?

It would be great if you could also update the diagram GIF (`/documentation/vscode-diagram.gif`) to match the new styling. Thanks!

**Comment by planger** [comment]
Thanks for the review!

> I noticed that the resizing of nodes does not work (as well as it doesn't on current master). The feature table at https://github.com/eclipse-glsp/glsp#features however states it should work. Therefore, due to the unsupported resizing, the category nodes are not properly supported in the VSCode diagram. Could you please have a look at that?

As this isn't related to this change, I think it'd be better to create a separate GH issue and PR for that.

> It would be great if you could also update the diagram GIF (`/documentation/vscode-diagram.gif`) to match the new styling. Thanks!

Yes, good point! I'll update this PR with a new GIF.

**Comment by planger** [comment]
I've created the new issue re resizing of nodes: https://github.com/eclipse-glsp/glsp/issues/516

**Comment by planger** [comment]
The GIFs were always pretty ugly (artifacts in the background), so I switched to MP4 which is nicely supported now too!

**Review by ndoschek — APPROVED** [review]
Thanks a lot Philip, the video looks great! :tada:

**Pull request merged**
