### PR TITLE
Issues/205

### PR DESCRIPTION
**Pull request by julia05**
This PR is part of the course "Advanced Model Engineering" conducted at the [Model Engineering lab](https://me.big.tuwien.ac.at/) of TU Wien in the [Business Informatics Group](https://www.big.tuwien.ac.at/). 

It handles the ServerMessageAction and shows error/warning/information messages from the server as VSCode notifications.

Closes issue [205](https://github.com/eclipse-glsp/glsp/issues/205).

### CODE REVIEW

**Comment by tortmayr** [comment]
@julia05 Thank you for your contribution!
Can you please sign the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php) for your email address? This is mandatory before we can integrate your fix.
Otherwise the change looks good to me!

**Review by tortmayr — CHANGES_REQUESTED** [review]
@julia05 Thank you for your contribution!
Can you please sign the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php) for your email address? This is mandatory before we can integrate your fix. In addition, there are some conflicts. Could you please resolve them by rebasing onto the latest master?
Otherwise the change looks good to me!

**Comment by julia05** [comment]
@tortmayr rebased and signed (https://accounts.eclipse.org/users/julia07)

**Comment by tortmayr** [comment]
@julia05 Unfortunately the ECA check still fails:
 ```
Could not validate the users ECA sign-off status. Please ensure that the e-mail address of all contributing accounts match a valid Eclipse Foundation account with a valid ECA.
```
At first glance it seems to me like your git config is wrong. The author information shows the value "Julia" for both the user name and email. Please make sure that the email is correct (i.e. matches the one of your ECA account)

**Comment by julia05** [comment]
@tortmayr thank you very much for the hint, fixed it

**Review by tortmayr — APPROVED** [review]

**Pull request merged**
